#ifndef _FUNCONFIG_H
#define _FUNCONFIG_H

#define CH32V003           1
#define FUNCONF_USE_UARTPRINTF  0
#define FUNCONF_USE_DEBUGPRINTF 1
#define FUNCONF_UART_PRINTF_BAUD 1200
#define UART_MODE_RX
#endif